# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Book App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'KeychainSwift'
  pod 'CheckBox'
  # Pods for Book App
#  pod 'Book App'
  target 'Book AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Book AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
